//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDataBase.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_UserRights
    {
        public string GID { get; set; }
        public string UID { get; set; }
        public string Id { get; set; }
    
        public virtual UserRights UserRights { get; set; }
        public virtual Group Group { get; set; }
    }
}
