//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDataBase.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFields
    {
        public string Name { get; set; }
        public string GUID { get; set; }
        public string Value { get; set; }
        public string TXT { get; set; }
        public string UID { get; set; }
        public string ID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
